name: Dev, Stage, and Prod Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          echo "building image"
          # docker build -t my-app .
          # docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          # docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
      - name: Deploy to Dev Environment
        uses: aws-actions/deploy-to-aws@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          deployment-group: dev
      - name: Ask for Stage and Prod Deployment
        uses: actions/checkout@v2
        run: |
          read -p "Do you want to deploy to Stage and Prod? (y/n) " -n 1 -r
          echo    # (optional) move to a new line
          if [[ $REPLY =~ ^[Yy]$ ]]
          then
            echo "Deploying to Stage and Prod..."
            curl -X POST \
              https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/stage-and-prod/deployments \
              -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              -H 'Content-Type: application/json' \
              -d '{"ref":"main","environment":"stage-and-prod"}'
          fi

  stage-and-prod:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Stage Environment
        uses: aws-actions/deploy-to-aws@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          deployment-group: stage
      - name: Ask for Prod Deployment
        uses: actions/checkout@v2
        run: |
          read -p "Do you want to deploy to Prod? (y/n) " -n 1 -r
          echo    # (optional) move to a new line
          if [[ $REPLY =~ ^[Yy]$ ]]
          then
            echo "Deploying to Prod..."
            curl -X POST \
              https://api.github.com/repos/${GITHUB_REPO}/actions/workflows/stage-and-prod/deployments \
              -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              -H 'Content-Type: application/json' \
              -d '{"ref":"main","environment":"prod"}'
          fi
      - name: Deploy to Prod Environment
        uses: aws-actions/deploy-to-aws@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          deployment-group: prod
