name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: echo Building Docker Image!

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Dev Environment
        run: |
          echo "Deploying to Dev Environment"

  deploy_to_stage:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Deploy to Stage Environment
        run: |
          echo "Deploying to Stage Environment"

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_stage
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Deploy to Prod Environment
        run: |
          echo "Deploying to Prod Environment"
