name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy_stage:
        description: 'Do you want to deploy to stage?'
        required: true
        type: choice
        options:
          - 'yes'
          - 'no'
        default: 'no'
      deploy_prod:
        description: 'Do you want to deploy to prod?'
        required: true
        type: choice
        options:
          - 'yes'
          - 'no'
        default: 'no'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: echo Building Docker Image!

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Dev Environment
        run: |
          echo "Deploying to Dev Environment"

  deploy_to_stage:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    if: ${{ github.event.inputs.deploy_stage == 'yes' }}
    steps:
      - name: Deploy to Stage Environment
        run: |
          echo "Deploying to Stage Environment"

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: deploy_to_stage
    if: ${{ github.event.inputs.deploy_prod == 'yes' }}
    steps:
      - name: Deploy to Prod Environment
        run: |
          echo "Deploying to Prod Environment"
