name: Manual Actions Pipeline

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Do you want to run this pipeline? (yes/no)'
        required: true
        default: 'yes'

jobs:
  create-branch:
    if: inputs.confirm == 'yes'  # Proceed only if 'yes' is selected
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'  # Replace with your release branch name
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up GitHub CLI
        run: |
          echo "Setting up GitHub CLI"
          sudo apt-get install gh -y  # Install GitHub CLI if not already installed

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: List Open Approved PRs
        id: list_prs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the GH_TOKEN
        run: |
          echo "Listing open approved PRs..."
          prs=$(gh pr list --state open --json number,title,headRefName,reviews --jq '.[] | select(.reviews | length > 0 and any(.state == "APPROVED")) | "\(.headRefName); \(.reviews[0].commit.oid)"')
          if [ -z "$prs" ]; then
            echo "No open approved PRs found."
            echo "branches=" >> $GITHUB_ENV  # Set an empty value if no PRs found
            echo "oids=" >> $GITHUB_ENV
          else
            branches=$(echo "$prs" | cut -d ';' -f 1 | tr '\n' ';' | sed 's/;$//')  # Extract branch names
            oids=$(echo "$prs" | cut -d ';' -f 2 | tr '\n' ';' | sed 's/;$//')  # Extract OIDs
            echo "branches=${branches}" >> $GITHUB_ENV
            echo "oids=${oids}" >> $GITHUB_ENV
            echo "List of branches: ${branches}"
            echo "List of OIDs: ${oids}"
          fi

      - name: Checkout or Cherry-Pick PRs
        id: cherry_pick
        run: |
          branches="${{ env.branches }}"  # Use the environment variable for branches
          oids="${{ env.oids }}"  # Use the environment variable for OIDs
          if [ -z "$branches" ]; then
            echo "No open approved PRs found."
            exit 0  # Exit gracefully if no PRs
          fi

          IFS=';'  # Use semicolon as a delimiter for both branches and OIDs
          branch_array=(${branches})
          oid_array=(${oids})

          for i in "${!branch_array[@]}"; do
            pr_branch=${branch_array[$i]}
            pr_oid=${oid_array[$i]}
            echo "Fetching branch $pr_branch..."
            git fetch origin "$pr_branch"  # Fetch the branch
            echo "Cherry-picking changes from commit $pr_oid..."
            git cherry-pick "$pr_oid" || { echo "Cherry-pick failed for commit $pr_oid"; exit 1; }
            ls
          done

      - name: List Files
        run: ls
