name: Manual Actions Pipeline

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Do you want to run this pipeline? (yes/no)'
        required: true
        default: 'no'

jobs:
  create-branch:
    if: inputs.confirm == 'yes'  # Proceed only if 'yes' is selected
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'  # Replace with your release branch name

      - name: List Open Approved PRs
        id: list_prs
        run: |
          echo "Listing open approved PRs..."
          prs=$(gh pr list --state open --json number,title,headRef,merged --jq '.[] | select(.merged == false) | "\(.number): \(.title) (\(.headRef))"')
          echo "$prs"
          echo "::set-output name=prs::$prs"

      - name: Checkout or Cherry-Pick PRs
        id: cherry_pick
        run: |
          prs="${{ steps.list_prs.outputs.prs }}"
          IFS=$'\n'
          for pr in $prs; do
            pr_ref=$(echo "$pr" | awk -F ' ' '{print $NF}')  # Extract the headRef
            echo "Cherry-picking changes from $pr_ref..."
            git fetch origin $pr_ref && git cherry-pick $pr_ref || { echo "Cherry-pick failed for $pr_ref"; exit 1; }
          done

      - name: List Files
        run: ls
