name: Build and Deploy

on:
  pull_request_review:
    types: [submitted]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' }}
    env:
      TARGET_ENV: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Build Source
        run: |
          echo "Building in environment $TARGET_ENV"

  build-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.event.pull_request.base.ref == 'branch1-dev' || github.event.pull_request.base.ref == 'branch2-stage' || github.event.pull_request.base.ref == 'branch3-prod' }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Docker Image and Push to Registry
        run: |
          echo "Building and pushing the image for ${{ github.event.pull_request.base.ref }}"
            
  deploy:
    runs-on: ubuntu-latest
    needs: build-push-docker-image
    if: ${{ github.event.pull_request.base.ref == 'branch1-dev' || github.event.pull_request.base.ref == 'branch2-stage' || github.event.pull_request.base.ref == 'branch3-prod' }}
    
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ github.event.pull_request.base.ref }}"
