name: Build and Deploy

on:
  pull_request_review:
    types: [submitted]

jobs:
  Checkout:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' }}
    env:
      TARGET_ENV: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Build Source
        run: |
          echo "Building in environment $TARGET_ENV"

  build-push-docker-image:
    runs-on: ubuntu-latest
    needs: Checkout
    if: ${{ github.event.pull_request.base.ref == 'dev'}}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Docker Image and Push to Registry
        run: |
          echo "Building and pushing the image for ${{ github.event.pull_request.base.ref }}"
            
  deploy:
    name: Deploying on ${{ github.event.pull_request.base.ref }}
    runs-on: ubuntu-latest
    needs: Checkout
    if: ${{ github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'stage' || github.event.pull_request.base.ref == 'prod' }}
    
    steps:
      - name: Deploy to ${{ github.event.pull_request.base.ref }}
        run: |
          echo "Deploying to ${{ github.event.pull_request.base.ref }}"
