name: Manual Actions Pipeline

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Do you want to run this pipeline? (yes/no)'
        required: true
        default: 'yes'

jobs:
  create-branch:
    if: inputs.confirm == 'yes'  # Proceed only if 'yes' is selected
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure write permissions

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v4
        with:
          ref: 'release'  # Replace with your release branch name

      - name: Create New Integration Branch
        run: |
          today=$(date +'%d%m%Y')
          new_branch="integration-$today"
          git checkout -b "$new_branch"
          echo "New branch created: $new_branch"
          echo "new_branch=${new_branch}" >> $GITHUB_ENV

      - name: Merge Approved PRs into New Branch
        run: |
          branches="${{ env.branches }}"
          if [ -z "$branches" ]; then
            echo "No open approved PRs found."
            exit 0  # Exit gracefully if no PRs
          fi
          
          IFS=';'  # Use semicolon as a delimiter for branches
          branch_array=(${branches})

          for pr_branch in "${branch_array[@]}"; do
            echo "Fetching branch $pr_branch..."
            git fetch origin "$pr_branch"  # Fetch the branch
            echo "Merging changes from origin/$pr_branch into ${{ env.new_branch }}..."
            git merge "origin/$pr_branch" || { echo "Merge failed for branch $pr_branch"; exit 1; }
          done

      - name: Push New Branch to Repo
        run: |
          git push origin "${{ env.new_branch }}"
