name: Start Workflow on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  run_on_approval:
    if: ${{ github.event.review.state == 'approved' }}  # Run only if the review is approved
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # Check out the code from the PR

    - name: checkout PR code 2
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run Tests
      run: npm test  # Example command, adjust based on your project needs

    - name: Deploy (if needed)
      run: ./deploy.sh  # Example deployment step, customize based on your deployment process
