name: Start Workflow on PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  run_on_approval:
    if: ${{ github.event.review.state == 'approved' }}  # Run only if the review is approved
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # Check out the code from the PR

    - name: List Files
      run: ls -la  # List all files and directories in long format
      
  deploy_to_stage:
    runs-on: ubuntu-latest
    needs: [run_on_approval]
    environment: staging-test
    steps:
      - name: Build Image Tag
        run: |
            IMAGE_TAG=$(date +'%Y%m%d')_${{github.ref_name}}_${{ github.run_number}}
            echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_ENV"
