name: Simple CI Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload test results (Optional)
      if: always()
      run: echo "Uploading results..."
    - name: Trigger Workflow in Another Repository
      run: |
          # Set the required variables
          repo_owner="pankajdevops2489"
          repo_name="sampleactionworkflow"
          event_type="trigger-workflow"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
