name: Build and Deploy Che-dashboard

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: artifactory-mb.harman.com:5036
  BITBUCKET_PROJECT: SPACE  
  REPO_NAME: environment-configuration-space
  TO_BRANCH: master

jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Build Image Tag
        id: set_tag
        run: |
          IMAGE_TAG=$(date +'%Y%m%d')_${{ github.ref_name }}_${{ github.run_number }}
          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_ENV"
          echo "::set-output name=image_tag::$IMAGE_TAG"

  build-push-docker-image:
    runs-on: ubuntu-latest
    needs: set-image-tag
    steps:
      - name: Build Docker Image and push to Registry
        run: |
          echo ${{ needs.set-image-tag.outputs.image_tag }}

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: set-image-tag
    steps:
      - name: Deploy to Dev Environment
        run: |
          echo ${{ needs.set-image-tag.outputs.image_tag }}

  deploy_to_stage:
    runs-on: ubuntu-latest
    needs: set-image-tag
    steps:
      - name: Deploy to Stage Environment
        run: |
          echo ${{ needs.set-image-tag.outputs.image_tag }}

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: set-image-tag
    steps:
      - name: Deploy to Prod Environment
        run: |
          echo ${{ needs.set-image-tag.outputs.image_tag }}
